// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/signup": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/signup";
  };
  "pages/index.tsx": {
    id: "pages/index";
    page: "/";
  };
  "pages/auth/login.tsx": {
    id: "pages/auth/login";
    page: "/auth/login";
  };
  "pages/auth/signup.tsx": {
    id: "pages/auth/signup";
    page: "/auth/signup";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/index": typeof import("./app/pages/index.tsx");
  "pages/auth/login": typeof import("./app/pages/auth/login.tsx");
  "pages/auth/signup": typeof import("./app/pages/auth/signup.tsx");
};